name: content-engine
recipe: drupal8
config:
  webroot: .
  php: '7.3'
  via: apache
  framework: drupal8
  # xdebug: true
  # config:
  #   php: .lando.php.ini

services:
  my-service:
    type: phpmyadmin
    hosts:
      - database
  database:
    type: mysql
  # appserver:
  #   overrides:
  #     environment:
  #       # Support debugging Drush with XDEBUG.
  #       PHP_IDE_CONFIG: "serverName=appserver"