<?php

/**
 * @file
 * Contains oauth_logout.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function oauth_logout_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the oauth_logout module.
    case 'help.page.oauth_logout':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('adds a logout route to the simple oauth module') . '</p>';
      return $output;

    default:
  }
}
