<?php

/**
 * @file
 * Contains triggered_events.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function triggered_events_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the triggered_events module.
    case 'help.page.triggered_events':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('events that can be attached via a plugin system to code') . '</p>';
      return $output;

    default:
  }
}

function triggered_events_mail ($key, &$message, $params) {
  switch ($key) {
    case 'mymail':
      // Set headers etc
      $message['to'] = 'hasnain@contentengine.com';
      $message['subject'] = t('Hello');
      $message['body'][] = t('Hello @username,', array('@username' => $params['username']));
      $message['body'][] = t('The main part of the message.');
      break;
  }
}
